/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.trabajo3.SwingElements.visuales;

import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import uam.trabajo3.SwingElements.clasesBase.Persona;

/**
 *
 * @author mario
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    
    ArrayList<JCheckBox> listaApoyos = new ArrayList<>(); 
    public Registro() {
        initComponents();
        agruparRadioButtons(); 
        agruparCheckBoxApoyos();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGenero = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        lblGenero = new javax.swing.JLabel();
        rbFemenino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        lblApoyos = new javax.swing.JLabel();
        cb3raEdad = new javax.swing.JCheckBox();
        cbDesempleo = new javax.swing.JCheckBox();
        cbSoltero = new javax.swing.JCheckBox();
        cbNini = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        lblLugar = new javax.swing.JLabel();
        cbCdmx = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO");
        setResizable(false);
        setSize(new java.awt.Dimension(560, 700));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("SISTEMA DE REGISTRO");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("NOMBRE: ");

        lblRfc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRfc.setText("RFC: ");

        lblCurp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCurp.setText("CURP: ");

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGenero.setText("GÉNERO: ");

        rbFemenino.setSelected(true);
        rbFemenino.setText("FEMENINO");

        rbMasculino.setText("MASCULINO");

        lblApoyos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblApoyos.setText("APOYOS: ");

        cb3raEdad.setText("3RA EDAD");

        cbDesempleo.setText("DESEMPLEO");

        cbSoltero.setText("MADRE/PADRE SOLTERO");

        cbNini.setText("NINI");

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblLugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLugar.setText("LUGAR DE ORIGEN: ");

        cbCdmx.setText("CDMX");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLugar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblCurp)
                                        .addComponent(lblRfc)
                                        .addComponent(lblGenero))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbFemenino)
                                            .addGap(45, 45, 45)
                                            .addComponent(rbMasculino))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(135, 135, 135)
                                            .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblApoyos)
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(cbCdmx)
                                            .addGap(36, 36, 36))
                                        .addComponent(cbDesempleo, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addComponent(cbSoltero)
                                    .addGap(18, 18, 18)
                                    .addComponent(cb3raEdad)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbNini))))))
                .addGap(85, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurp)
                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRfc)
                    .addComponent(txtRfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblGenero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbFemenino)
                            .addComponent(rbMasculino))))
                .addGap(27, 27, 27)
                .addComponent(lblLugar)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblApoyos)
                        .addGap(83, 83, 83))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbCdmx)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDesempleo)
                            .addComponent(cbSoltero)
                            .addComponent(cb3raEdad)
                            .addComponent(cbNini))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnRegistrar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        // obtenemos el bombre, curp y rfc
        String nombre = txtNombre.getText(); 
        String curp = txtCurp.getText(); 
        String rfc = txtRfc.getText(); 
        
        //ahora tenemos que obtener el valor del genero 
        String genero = seleccionarGenero(); 
        
        // obtenemos los apoyos seleccionados 
        ArrayList<String> apoyos = obtenerListaApoyos(); 
        
        // obtenemos el lugar de origen 
        String direccion = "Otro Estado"; 
        if(cbCdmx.isSelected()){
           direccion = "CDMX";
        }
        
        //creamos a la persona 
        Persona persona = new Persona(nombre, curp, rfc, genero, direccion, apoyos); 
        System.out.println("-----------------------------------------------------");
        System.out.println(persona.toString());
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    
    public void agruparRadioButtons(){
        btnGroupGenero.add(rbFemenino);
        btnGroupGenero.add(rbMasculino);
    }
    
    public void agruparCheckBoxApoyos(){
        listaApoyos.add(cbDesempleo);
        listaApoyos.add(cb3raEdad);
        listaApoyos.add(cbNini);
        listaApoyos.add(cbSoltero);
    }
   
    public String seleccionarGenero(){
        Enumeration <AbstractButton> btnGroup = btnGroupGenero.getElements(); 
        String genero = ""; 
        while(btnGroup.hasMoreElements()){
            JRadioButton btnAux = (JRadioButton) btnGroup.nextElement(); 
            if(btnAux.isSelected()){
                genero = btnAux.getText(); 
                break; 
            }
        }
        return genero; 
    }
    
    public ArrayList<String> obtenerListaApoyos(){
        ArrayList<String> lista = new ArrayList<>(); 
        for(int i = 0; i < listaApoyos.size(); ++i){
            if(listaApoyos.get(i).isSelected()){
                lista.add(listaApoyos.get(i).getText());
            }
        }
        return lista; 
    }
    
  
    
    public void limpiarCampos(){
        txtNombre.setText("");
        txtCurp.setText("");
        txtRfc.setText("");
        for(JCheckBox aux : listaApoyos){
            aux.setSelected(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGenero;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JCheckBox cb3raEdad;
    private javax.swing.JCheckBox cbCdmx;
    private javax.swing.JCheckBox cbDesempleo;
    private javax.swing.JCheckBox cbNini;
    private javax.swing.JCheckBox cbSoltero;
    private javax.swing.JLabel lblApoyos;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLugar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
